### ISSUE TITLE
无法使用，log 报"status":502

### ISSUE THREAD

**Issue by alexbyrant0** [DaoChen6/IF-XTW#11]

**Comment by Dimitri2020007** [comment]
pr通过之后重新fo一下

**Comment by DaoChen6** [comment]
#7 #10 已通过pr，重新试试

**Comment by alexbyrant0** [comment]
重新fo后还是报502，bad gateway
"status":502,"err_id":"ejjjy6e48","err_trace":"reverseproxy.statusError (reverseproxy.go:886)"
还请帮忙看看

**Comment by Dimitri2020007** [comment]
> 重新fo后还是报502，bad gateway "status":502,"err_id":"ejjjy6e48","err_trace":"reverseproxy.statusError (reverseproxy.go:886)" 还请帮忙看看

这回pr通过之后再试试

**Comment by Dimitri2020007** [comment]
> 重新fo后还是报502，bad gateway "status":502,"err_id":"ejjjy6e48","err_trace":"reverseproxy.statusError (reverseproxy.go:886)" 还请帮忙看看

可以删除再重新fork一遍了

连接方式已修复

**Comment by alexbyrant0** [comment]
可以啦，多谢~
