### ISSUE TITLE
StoreFiles是做什么用的？

### ISSUE THREAD

**Issue by Maryookout** [DaoChen6/IF-XTW#23]
看到项目里面有StoreFiles这个文件，但是不知道这个文件是起到什么作用呢？可以介绍一下要怎么用呢？

**Comment by Dimitri2020007** [comment]
那个是为了下载服务端执行文件的

基本不用管

**Comment by Maryookout** [comment]
> 那个是为了下载服务端执行文件的
> 
> 基本不用管

如果删除掉这个变量了，那会连接不上吗？

**Comment by Maryookout** [comment]
那是否可以在每次启动的时候能自动判断更新到最新的Xray或者v2ray？？

**Comment by Dimitri2020007** [comment]
> 

是的

**Comment by Dimitri2020007** [comment]
> > 那个是为了下载服务端执行文件的
> > 基本不用管
> 
> 如果删除掉这个变量了，那会连接不上吗？

是的

**Comment by Maryookout** [comment]
为什么要在项目里安装tor呢？是为了隐私吗？还是为了安全考虑的？

**Comment by Dimitri2020007** [comment]
> 为什么要在项目里安装tor呢？是为了隐私吗？还是为了安全考虑的？

隐私和安全因素都有

**Comment by Dimitri2020007** [comment]
> 那是否可以在每次启动的时候能自动判断更新到最新的Xray或者v2ray？？

这个我目前还没办法测试，因为没推新版本。

可以在重启dyno的时候试试

**Comment by Maryookout** [comment]
> 

那这么说的话最终的出口流量走是Tor，如果是走Tor流量的话，那速度会受限制吗？

**Comment by Maryookout** [comment]
> > 为什么要在项目里安装tor呢？是为了隐私吗？还是为了安全考虑的？
> 
> 隐私和安全因素都有

那这么说的话最终的出口流量走是Tor，如果是走Tor流量的话，那速度会受限制吗？

**Comment by Dimitri2020007** [comment]
> > > 为什么要在项目里安装tor呢？是为了隐私吗？还是为了安全考虑的？
> > 
> > 
> > 隐私和安全因素都有
> 
> 那这么说的话最终的出口流量走是Tor，如果是走Tor流量的话，那速度会受限制吗？

不会，基于路由规则分流处理。

**Comment by Maryookout** [comment]
> 



> > > > 为什么要在项目里安装tor呢？是为了隐私吗？还是为了安全考虑的？
> > > 
> > > 
> > > 隐私和安全因素都有
> > 
> > 
> > 那这么说的话最终的出口流量走是Tor，如果是走Tor流量的话，那速度会受限制吗？
> 
> 不会，基于路由规则分流处理。

这个问题可以帮忙删除掉了，谢谢交流，不打扰了。
