### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Maryookout** [DaoChen6/IF-XTW#24]
2021-12-05T13:58:31.991096+00:00 app[web.1]: ls: /usr/share/caddy/5a8××××-5103d19834d1: No such file or directory

不知道是怎么回事呢？是 Dockerfile 没写好吗？

**Comment by Maryookout** [comment]
不知道会不会影响使用呢？

**Comment by Dimitri2020007** [comment]
会连不上节点

删除本项目重新fork一遍再试试

**Comment by Maryookout** [comment]
> 会连不上节点
> 
> 删除本项目重新fork一遍再试试

我们是昨天才fork的，应该没问题吧，都测试多次了

**Comment by Dimitri2020007** [comment]
重新部署

**Comment by Maryookout** [comment]
> 重新部署

/usr/share/caddy/$AUUID/StoreFiles，部署的时候，$AUUID这个变量不知道为啥没用

**Comment by Maryookout** [comment]
昨天部署的时候，查看了部署日志，这个变量没生效

**Comment by Maryookout** [comment]
你有测试吗？

**Comment by Dimitri2020007** [comment]
我都是是测试过了才修改的

而且你仓库中的版本和现在这个是不一样的

**Comment by Maryookout** [comment]
> 我都是是测试过了才修改的
> 
> 而且你仓库中的版本和现在这个是不一样的

我仓库这个是老的，我们昨天测试的是你修改好的那个

**Comment by Dimitri2020007** [comment]
> > 我都是是测试过了才修改的
> > 而且你仓库中的版本和现在这个是不一样的
> 
> 我仓库这个是老的，我们昨天测试的是你修改好的那个

连接给出来

**Comment by Maryookout** [comment]
> 我都是是测试过了才修改的
> 
> 而且你仓库中的版本和现在这个是不一样的

要不过后重新测试一下，有问题再跟你交流吧。

**Comment by Maryookout** [comment]
> > > 我都是是测试过了才修改的
> > > 而且你仓库中的版本和现在这个是不一样的
> > 
> > 
> > 我仓库这个是老的，我们昨天测试的是你修改好的那个
> 
> 连接给出来

你要的什么连接？？？

**Comment by Dimitri2020007** [comment]
你说改好的那个啊

**Comment by Maryookout** [comment]
> 你说改好的那个啊

我昨天测试没用，就删除掉了

**Comment by Dimitri2020007** [comment]
fork这个连接

https://github.com/DaoChen6/IF-XTW.git

**Comment by Maryookout** [comment]
> fork这个连接
> 
> https://github.com/DaoChen6/IF-XTW.git

好的，谢谢，过后测试好再跟你说吧

**Comment by Dimitri2020007** [comment]
不要fork我名字底下的同名项目

那个是不稳定的
