### ISSUE TITLE
'/usr/share/caddy//StoreFiles'中间的$AUUID没生效

### ISSUE THREAD

**Issue by Maryookout** [DaoChen6/IF-XTW#27]
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.

HTTP request sent, awaiting response... 200 OK

Length: 274 [text/plain]

Saving to: '/usr/share/caddy//StoreFiles'

     0K                                                       100% 20.1M=0s

2021-12-06 14:02:36 (20.1 MB/s) - '/usr/share/caddy//StoreFiles' saved [274/274]

**Comment by Dimitri2020007** [comment]
是否影响连接

**Comment by Dimitri2020007** [comment]
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
> 
> HTTP request sent, awaiting response... 200 OK
> 
> Length: 274 [text/plain]
> 
> Saving to: '/usr/share/caddy//StoreFiles'
> 
> ```
>  0K                                                       100% 20.1M=0s
> ```
> 
> 2021-12-06 14:02:36 (20.1 MB/s) - '/usr/share/caddy//StoreFiles' saved [274/274]

日志是部署时的还是进了app截取的？

**Comment by Maryookout** [comment]
> 是否影响连接?
> 
> 如果没生效部署是过不去的

连接不会受到影响
