### ISSUE TITLE
Qv2ray 运行报错是什么问题？

### ISSUE THREAD

**Issue by Maryookout** [DaoChen6/IF-XTW#29]
2021/12/07 12:51:00 [Warning] [4208628488] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://josephnsmith.herokuapp.com/89575723-4e49-452b-a7bb-a66c624fbe57-vless):  > io: read/write on closed pipe] > common/retry: all retry attempts failed
2021/12/07 12:51:00 [Warning] [1310324225] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://josephnsmith.herokuapp.com/89575723-4e49-452b-a7bb-a66c624fbe57-vless):  > io: read/write on closed pipe] > common/retry: all retry attempts failed
2021/12/07 12:51:00 [Warning] [2295766033] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://josephnsmith.herokuapp.com/89575723-4e49-452b-a7bb-a66c624fbe57-vless):  > io: read/write on closed pipe] > common/retry: all retry attempts failed
2021/12/07 12:51:00 [Warning] [1085462724] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://josephnsmith.herokuapp.com/89575723-4e49-452b-a7bb-a66c624fbe57-vless):  > io: read/write on closed pipe] > common/retry: all retry attempts failed
2021/12/07 12:51:00 [Warning] [1645441993] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://josephnsmith.herokuapp.com/89575723-4e49-452b-a7bb-a66c624fbe57-vless):  > io: read/write on closed pipe] > common/retry: all retry attempts failed

**Comment by Dimitri2020007** [comment]
QV2ray项目已经停止更新

用别的客户端吧

**Comment by Maryookout** [comment]
> 



> QV2ray项目已经停止更新
> 
> 用别的客户端吧
> 
> 你没有咨询阅读过注意事项吗
> 
> 带有删除线的内容是不适用或已经废弃的

那知道了
