### ISSUE TITLE
create app失败

### ISSUE THREAD

**Issue by Jacobax** [DaoChen6/IF-XTW#30]
改了仓库名及文件name，改了deploy链接
![Screenshot_2021-12-08-03-42-33-54_d0ef7a9810af20f7b394f4f927b723b0.jpg](https://user-images.githubusercontent.com/23228895/145096025-e5e0412a-21f9-4a34-9c10-e6b94a2a149c.jpg)

**Comment by DaoChen6** [comment]
修改description值了吗

**Comment by Dimitri2020007** [comment]
> 改了仓库名及文件name，改了deploy链接 ![Screenshot_2021-12-08-03-42-33-54_d0ef7a9810af20f7b394f4f927b723b0.jpg](https://user-images.githubusercontent.com/23228895/145096025-e5e0412a-21f9-4a34-9c10-e6b94a2a149c.jpg)

网络不稳定的时候会出现这个问题

不要用手机部署

**Comment by Jacobax** [comment]
刚又试了，换IP后可以了，感谢大佬的付出
