### ISSUE TITLE
请将项目移动到gitlab

### ISSUE THREAD

**Issue by Dimitri2020007** [DaoChen6/IF-XTW#31]
我的其中一个库已经被该平台（不是heroku）给禁用了

以防万一

在这提前提个醒

**Comment by willaytoun** [comment]
我试着把项目导过去，不过部署的时候Heroku就卡在这里了，这超出我的能力范围了😂
![image](https://user-images.githubusercontent.com/43229736/147868670-561aa666-312e-40f7-9cbb-a7f71295d8d4.png)

**Comment by DaoChen6** [comment]
我导入到gitlab了 做个备份 没测效果

**Comment by willaytoun** [comment]
好的 那就交给您测试了😀
