### ISSUE TITLE
SS配置表格里Path路径应为/自定义UUID码-ss

### ISSUE THREAD

**Issue by willaytoun** [DaoChen6/IF-XTW#32]
这边写成了：/自定义UUID码-trojan

![image](https://user-images.githubusercontent.com/43229736/147769288-b37a4d23-2966-408f-b1e1-dbcaa91738f2.png)

**Comment by Dimitri2020007** [comment]
> 这边写成了：/自定义UUID码-trojan
> 
> ![image](https://user-images.githubusercontent.com/43229736/147769288-b37a4d23-2966-408f-b1e1-dbcaa91738f2.png)

哦，那是小问题，我马上着手修复。

谢谢你的提醒。

请删除本项目后重新fork一遍并将用户名改成自己的，顺便在fork后改项目名字。

**Comment by willaytoun** [comment]
嗯嗯 已经fork后改名字并顺利搭建😀

不过我这边试了几个号和几个协议速度都上不去，刚开始搭好可以上5M+但是大概3分钟之后就只有100K左右了，我试了联通和移动网都是这样手机流量也是，不知道是我这边的问题还是heroku检测到限了速

**Comment by DaoChen6** [comment]
请自选IP以达最佳效果

**Comment by DaoChen6** [comment]
另外动态优选IP域名已在计划中 届时可不经常改动便达最佳效果

**Comment by willaytoun** [comment]
用CloudflareST优选IP速度100K不用的话基本连不上，其它廉价VPS套CF可以跑5M左右。

因为之前用Heroku速度在2M左右，我不知道是不是最近Heroku限速了。

**Comment by Dimitri2020007** [comment]
@DaoChen6 是不是可以考虑下okteto平台了

不过需要gitlab部署，github过夜就ban

**Comment by DaoChen6** [comment]
> @DaoChen6 是不是可以考虑下okteto平台了
> 
> 不过需要gitlab部署，github过夜就ban

我觉得可以试试

**Comment by DaoChen6** [comment]
> 用CloudflareST优选IP速度100K不用的话基本连不上，其它廉价VPS套CF可以跑5M左右。
> 
> 因为之前用Heroku速度在2M左右，我不知道是不是最近Heroku限速了。

我优选IP 谷歌云盘下载东西 17MB/s左右诶

**Comment by willaytoun** [comment]
哦哦 那应该和我网络有关或者是用过之前被封的脚本

**Comment by willaytoun** [comment]
> 另外动态优选IP域名已在计划中 届时可不经常改动便达最佳效果

使用了最新的动态优选IP速度很快，感谢您😀
