### ISSUE TITLE
桌面版的v2ray客户端突然用不了

### ISSUE THREAD

**Issue by gentlelion99** [DaoChen6/IF-XTW#33]
不知道怎么回事

**Comment by DaoChen6** [comment]
我可以使用，请重新部署或是带上你的错误日志、提示

**Comment by gentlelion99** [comment]
是突然的 
v2ray 桌面提示：2022/01/07 16:13:00 tcp:127.0.0.1:49510 accepted tcp:mail.google.com:443 [proxy] 
2022/01/07 16:13:00 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)

**Comment by gentlelion99** [comment]
重新部署也是不能使用 部署过程没有错误

**Comment by gentlelion99** [comment]
手机端就完全正常

**Comment by DaoChen6** [comment]
请提供配置截图

**Comment by Dimitri2020007** [comment]
提供配置截图，关键信息请处理掉以免发生不必要的麻烦

**Comment by gentlelion99** [comment]
![1](https://user-images.githubusercontent.com/55936417/148625466-95cac36c-695c-4435-9a31-fe6e3117e720.jpg)

**Comment by DaoChen6** [comment]
allowInsecure 选择false 填上SNI

**Comment by Dimitri2020007** [comment]
> ![1](https://user-images.githubusercontent.com/55936417/148625466-95cac36c-695c-4435-9a31-fe6e3117e720.jpg)

你的pc客户端太老了，更新最新的客户端。

allowinsecure 选false 填上sni

**Comment by DaoChen6** [comment]
@Dimitri2020007 加个q

**Comment by Dimitri2020007** [comment]
> @Dimitri2020007 加个q

国产的所有社交app是不能讨论这个问题的

**Comment by DaoChen6** [comment]
> > @Dimitri2020007 加个q
> 
> 国产的所有社交app是不能讨论这个问题的

加个tg
iflmi

**Comment by gentlelion99** [comment]
> > @Dimitri2020007 加个q
> 
> 国产的所有社交app是不能讨论这个问题的

是啊

**Comment by gentlelion99** [comment]
> > > @Dimitri2020007 加个q
> > 
> > 
> > 国产的所有社交app是不能讨论这个问题的
> 
> 是啊

是突然一晚上过后就不能用了

**Comment by gentlelion99** [comment]
我换成Xray试试

**Comment by gentlelion99** [comment]
> 我换成Xray试试

不会写json

**Comment by Dimitri2020007** [comment]
> 我换成Xray试试

在更新xray之前将桌面的客户端升级到最新版本

**Comment by gentlelion99** [comment]
> 我可以使用，请重新部署或是带上你的错误日志、提示

大佬可以分享一下xray客户端配置模板吗
不知道怎么填

**Comment by Dimitri2020007** [comment]
xray和v2ray的配置模板是一样的

**Comment by gentlelion99** [comment]
![stop](https://user-images.githubusercontent.com/55936417/149432113-e4e6f0ac-8a13-4f6e-8b45-f6486631b44d.jpg)
代码不能用了

**Comment by Dimitri2020007** [comment]
> ![stop](https://user-images.githubusercontent.com/55936417/149432113-e4e6f0ac-8a13-4f6e-8b45-f6486631b44d.jpg) 代码不能用了

heroku防止同一项目恶意滥用，修改项目名。

**Comment by gentlelion99** [comment]
> > ![stop](https://user-images.githubusercontent.com/55936417/149432113-e4e6f0ac-8a13-4f6e-8b45-f6486631b44d.jpg) 代码不能用了
> 
> heroku防止同一项目恶意滥用，修改项目名。不一定会有效。

最近有什么新的方法出现吗 大佬自己写一个？

**Comment by Dimitri2020007** [comment]
account delete enabled

......5
......4
......3
......2
......1

====================>Account has been deleted ！Thank you for your cooperation<===================

**Comment by gentlelion99** [comment]
> account delete enabled
> 
> ......5 ......4 ......3 ......2 ......1
> 
> ====================>Account has been deleted ！Thank you for your cooperation<===================
> 
> #goodbye github

准备硬刚saleforce吗 大佬

**Comment by Cptmacmillan2022007** [comment]
硬刚是不可能的，他已经删除了他的账户

**Comment by gentlelion99** [comment]
> 硬刚是不可能的，他已经删除了他的账户

大佬 目前能配置GCP服务端的专案有吗

**Comment by Cptmacmillan2022007** [comment]
没有了
