### ISSUE TITLE
是不是heroku动手了，部署了几遍都是这样

### ISSUE THREAD

**Issue by jgsports** [DaoChen6/IF-XTW#39]
Downloaded: 1 files, 8.9M in 0.2s (44.2 MB/s)

chmod: /xray: No such file or directory

The command '/bin/sh -c apk update &&     apk add --no-cache --virtual ca-certificates caddy tor wget &&     mkdir /v2ray &&     wget -qO- https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip | busybox unzip - &&     mkdir -p /usr/share/caddy/$AUUID && wget -O /usr/share/caddy/$AUUID/StoreFiles https://raw.githubusercontent.com/DaoChen6/IF-XTW/master/etc/StoreFiles &&     wget -P /usr/share/caddy/$AUUID -i /usr/share/caddy/$AUUID/StoreFiles &&     chmod +x /xray &&     rm -rf /var/cache/apk/*' returned a non-zero code: 1

**Comment by DaoChen6** [comment]
请删除你fork的仓库重新fork

**Comment by jgsports** [comment]
重新fork了，该修改的都修改了，还换了个heroku的id，还是如此。估计heroku下手了，需要改名和加密xray，大神可以参考下

**Comment by Cptmacmillan2022007** [comment]
> Downloaded: 1 files, 8.9M in 0.2s (44.2 MB/s)
> 
> chmod: /xray: No such file or directory
> 
> The command '/bin/sh -c apk update && apk add --no-cache --virtual ca-certificates caddy tor wget && mkdir /v2ray && wget -qO- https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip | busybox unzip - && mkdir -p /usr/share/caddy/$AUUID && wget -O /usr/share/caddy/$AUUID/StoreFiles https://raw.githubusercontent.com/DaoChen6/IF-XTW/master/etc/StoreFiles && wget -P /usr/share/caddy/$AUUID -i /usr/share/caddy/$AUUID/StoreFiles && chmod +x /xray && rm -rf /var/cache/apk/*' returned a non-zero code: 1

提供deploy的日志
