### ISSUE TITLE
最近heroku的https证书失效不能用了

### ISSUE THREAD

**Issue by bigbrotherff2** [DaoChen6/IF-XTW#46]
昨天晚上开始v2ray报错，打开创建的app实例发现https证书失效了，大家还能用吗
app/proxyman/outbound: failed to process outbound traffic > proxy/trojan: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to

**Comment by pingshu** [comment]
昨天开始不能用了

**Comment by bigbrotherff2** [comment]
发现是CF反代炸了，直连是没问题的

**Comment by Cptmacmillan2022007** [comment]
> 发现是CF反代炸了，直连是没问题的

我测试了一下确实是你说的这种情况。app直连成功就是速度慢的受不了。具体情况看看cf是不是修好了。

修好的给捎个信

另外heroku的筒子们请重新设置下密码以免用不了heroku账号，重设之后还是可以放心用的。

**Comment by DaoChen6** [comment]
cf反代域名已墙，请绑定上自己的域名

**Comment by SocialWil** [comment]
> cf反代域名已墙，请绑定上自己的域名

cf反代可以使用，不知道cf现在是不是修复好了

**Comment by SocialWil** [comment]
> > 发现是CF反代炸了，直连是没问题的
> 
> 我测试了一下确实是你说的这种情况。app直连成功就是速度慢的受不了。具体情况看看cf是不是修好了。
> 
> 修好的给捎个信
> 
> 另外heroku的筒子们请重新设置下密码以免用不了heroku账号，重设之后还是可以放心用的。

现在CF是被墙了没，我这边还好好的。

**Comment by DaoChen6** [comment]
已墙，请参考readme

**Comment by Cptmacmillan2022007** [comment]
> 已墙，请参考readme

readme中提示的方法无效

**Comment by davoola** [comment]
绑定域名后有效，速度不变

**Comment by pingshu** [comment]
能否出了详细的教程啊，https://www.ifts.ml/posts/Cloudflare-Workers-Add-domain-name  里的太简单了看不懂

**Comment by davoola** [comment]
> 能否出个详细的教程啊，https://www.ifts.ml/posts/Cloudflare-Workers-Add-domain-name 里的太简单了看不懂

CF里只要有域名即可，然后按照上面的教程来，很简单呀。仔细看一下。

**Comment by pingshu** [comment]
在Cloudflare中添加自己的域名  https://baijiahao.baidu.com/s?id=1730341061938823494&wfr=spider&for=pc
是按照这个教程设置吗

**Comment by DaoChen6** [comment]
> 在Cloudflare中添加自己的域名 https://baijiahao.baidu.com/s?id=1730341061938823494&wfr=spider&for=pc 是按照这个教程设置吗

不是，这个是获取免费域名教程，你可以试试，然后cloudflare里添加域名，更改域名DNS为cloudflare指定DNS服务器

**Comment by davoola** [comment]
> 在Cloudflare中添加自己的域名 https://baijiahao.baidu.com/s?id=1730341061938823494&wfr=spider&for=pc 是按照这个教程设置吗

在CF里面添加站点，然后在域名注册商那边修改对应的NamesServers即可。如果是在Freenom上面注册的域名，按上面教程来即可，最后一步证书那块可以不用操作

**Comment by Cptmacmillan2022007** [comment]
> > 在Cloudflare中添加自己的域名 https://baijiahao.baidu.com/s?id=1730341061938823494&wfr=spider&for=pc 是按照这个教程设置吗
> 
> 不是，这个是获取免费域名教程，你可以试试，然后cloudflare里添加域名，更改域名DNS为cloudflare指定DNS服务器

我dns都指定了还要怎么做

**Comment by pingshu** [comment]
"路由填写域名前缀.你的域名/*"
请问前缀是什么？

**Comment by DaoChen6** [comment]
> "路由填写域名前缀.你的域名/*" 请问前缀是什么？

随便

**Comment by Cptmacmillan2022007** [comment]
需要添加域名记录吗？

**Comment by DaoChen6** [comment]
> > 已墙，请参考readme
> 
> readme中提示的方法无效，而且isp到workers连接被阻断了。
> 
> workers连接容器的网络是正常的。
> 
> 与是否修复无关。

有效

**Comment by DaoChen6** [comment]
> 需要添加域名记录吗？

无需

**Comment by Cptmacmillan2022007** [comment]
> > 需要添加域名记录吗？
> 
> 无需，然后节点记得更改Host和SNI值为自己域名，建群了，tg群里聊吧，README里有地址

前缀必须和cname绑定

cname必须指定到workers

**Comment by DaoChen6** [comment]
> > > 需要添加域名记录吗？
> > 
> > 
> > 无需，然后节点记得更改Host和SNI值为自己域名，建群了，tg群里聊吧，README里有地址
> 
> 前缀必须和cname绑定
> 
> cname必须指定到workers

真心不需要。。。。

**Comment by Cptmacmillan2022007** [comment]
可以考虑下zero trust通道
