### ISSUE TITLE
无法部署，提示源代码违反政策

### ISSUE THREAD

**Issue by royaldeng2020** [DaoChen6/IF-XTW#49]
# 在提出问题前请先自行排除服务器端问题和升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。
# 涉及IPv4/v6、反代IP/URL、APP URL、UUID、PATH等关键信息请删除，以免信息泄露引发更大麻烦。

# 1.关于你要提交的问题

Q：是否搜索了issue（使用“x”选择）
* [ ]没有类似的issue

# 2.预期行为
描述你认为应该发生什么

# 3.实际行为
描述实际发生了什么

# 4.复现方法

# 5.所使用的客户端（关键信息请删除！！！）

# 6.详细日志（关键信息请删除！！！）

**请提供Build app日志**

<请在此粘贴Build app日志>

**请提供Application Logs日志**

<请在此粘贴Application Logs日志>

**Comment by Cptmacmillan2022007** [comment]
请仔细阅读readme之后再来说这个问题。
