### ISSUE TITLE
caddy 问题

### ISSUE THREAD

**Issue by hhh222gff** [DaoChen6/IF-XTW#6]
到build app 那里突然停住了，试了几次不行，下面是提示

2021/12/02 07:38:55 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /usr/bin/caddy -ldflags -w -s -trimpath

**Comment by Dimitri2020007** [comment]
那是正常的，若网页卡住没反应直接刷新就好了

**Comment by hhh222gff** [comment]
谢谢回复，不过好像不是网页卡住，网页、鼠标都可以操作的，刷新我也试过了，重新开始还是没解决。。。。

**Comment by Dimitri2020007** [comment]
卡到这一步的时候exec (timeout=0s): /usr/local/go/bin/go build -o /usr/bin/caddy -ldflags -w -s -trimpath

点击左上角heroku看看有没有app

有app就成功了

**Comment by Dimitri2020007** [comment]
pr更新通过后重新fo一下就好

**Comment by hhh222gff** [comment]
这次可以了，谢谢

**Comment by Dimitri2020007** [comment]
请删除后重新fork

**Comment by Dimitri2020007** [comment]
> 这次可以了，谢谢

连接方式已修复

可以删除并重新fork
