### ISSUE TITLE
部署是成功了，但是测试已经开始报503了

### ISSUE THREAD

**Issue by NetBoy855** [DaoChen6/IF-XTW#8]

**Comment by Dimitri2020007** [comment]
删除后重新fo本项目

还是出现503的话基本是无解的

能正常访问就无须太担心这个

**Comment by pingshu** [comment]
重新部署虽然成功，但是还是503连接错误，是今天才出问题的，昨天以前一直都能用

**Comment by Dimitri2020007** [comment]
等待pr通过后再重新fo一下

**Comment by pingshu** [comment]
‘’ pr通过后再重新fo一下“ 是啥意思啊

**Comment by DaoChen6** [comment]
#7 #10 已通过pr，删除fork的仓库重新fork再部署试试

**Comment by Dimitri2020007** [comment]
等待加急更新通过再fo

**Comment by Dimitri2020007** [comment]
连接方式已修复

可以删除并重新fork

**Comment by Dimitri2020007** [comment]
> _No description provided._

连接方式已修复

可以删除并重新fork

**Comment by Dimitri2020007** [comment]
> ‘’ pr通过后再重新fo一下“ 是啥意思啊

连接方式已修复

可以删除并重新fork
